### ISSUE TITLE
plugin-info-schema.json add compatibility -> minimumVersion

### ISSUE THREAD

**Issue by Haehnchen** [shopwareLabs/plugin-info#1]
iam want to use `plugin-info-schema.json` as ide completion source. so it would be nice to integrate children option also. eg `compatibility -> minimumVersion`

**Comment by bcremer** [comment]
Thanks @Haehnchen for implementing this in the [Shopware PHPStorm Plugin](https://github.com/Haehnchen/idea-php-shopware-plugin/commit/b86bcbaa515949eaffbd02f26a83362f969bf2dd).

I hope the fix in https://github.com/shopwareLabs/plugin-info/pull/2 solves your issue.

I am a bit unsure how to describe the `changelog` property, maybe you have an idea?

**Comment by mitelg** [comment]
closing as not relevant anymore
