### ISSUE TITLE
Create XML Schema

### ISSUE THREAD

**Issue by bcremer** [shopwareLabs/plugin-info#3]
plugin-info.xml:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<plugin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="plugin.xsd">

    <label lang="de">My plugin</label>
    <version>1.5.3</version>
    <copyright>(c) Hansa Corp.</copyright>
    <license>MIT</license>
    <link>Some link</link>
    <author>Hasna Corp.</author>

    <changelog version="1.0.6">
        <changes lang="DE">German changes</changes>
        <changes lang="DE">English changes</changes>
    </changelog>

    <changelog version="1.0.5">
        <changes lang="DE">German changes</changes>
        <changes lang="DE">English changes</changes>
    </changelog>

    <compatibility minVersion="5.1.0" maxVersion="5.2.5">
        <blacklist>5.1.2</blacklist>
        <blacklist>5.1.3</blacklist>
    </compatibility>
</plugin>
```

menu.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../engine/Shopware/Components/Plugin/schema/menu.xsd">

    <entries>
        <entry>
            <label>SwagDefaultSort</label>
            <controller>SwagDefaultSort</controller>
            <action>index</action>
            <class>sprite-sort</class>
            <active>false</active>
            <position>-1</position>
            <parent identifiedBy="label">Einstellungen</parent>
        </entry>
    </entries>
</menu>
```

config.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../engine/Shopware/Components/Plugin/schema/config.xsd">

    <elements>
        <element scope="local" required="true" type="text">
            <label lang="de">Mein textfeld</label>
            <label lang="en">My Textfield</label>
            <value>Some default value</value>
            <description lang="de">Meine Feld Beschreibung</description>
            <description lang="en">My Field description</description>
        </element>

        <element scope="local" required="true" type="select">
            <label lang="de">Meine Selektion</label>
            <label lang="en">My Selection</label>
            <value>1</value>
            <description lang="de">Meine Feld Beschreibung</description>
            <description lang="en">My Field description</description>
            <store>
                <![CDATA[
array(
    array(1, 'Testvariable 1'),
    array(2, 'Testvariable 2'),
    array(3, 'Testvariable 3')
)
                ]]>
            </store>
        </element>
    </elements>
</config>
```

**Comment by dnoegel** [comment]
Regarding the changelogs: The old json-System forced us to have mutliple changes semicolon-separated, which was hard to maintain and read. 
What about making it somewhat more explicit. Also perhaps it makes sense to have version and language attributes per changelog? (not sure about that one)

``` xml
<changelogs>
    <changelog version="1.0.6" lang="EN"> 
        <change>Fix attributes</change>
        <change>Minor bugfixed</change>
    </changelog>
    <changelog version="1.0.6" lang="DE"> 
        <change>Korrektur Kunden-Attribut</change>
        <change>Kleinere Fehlerkorrekturen</change>
    </changelog>
</changelogs>
```

**Comment by dnoegel** [comment]
As an alternative, which is more similar to your initial suggestion:

``` xml
<changelogs>
    <changelog version="1.0.6"> 
        <changes lang="EN">
            <change>Fix attributes</change>
            <change>Minor bugfixed</change>
        </changes>
        <changes lang="DE">
            <change>Korrektur Kunden-Attribut</change>
            <change>Kleinere Fehlerkorrekturen</change>
        </changes>
    </changelog>
</changelogs>
```

**Comment by dnoegel** [comment]
Also we could discuss the description system. Will we keep the "per language text files", or do we move it to the XML as well? Markdown?
I think that XML might cover this as well - it would have been a pain in JSON but with a CDATA tag it might be quite convenient. But if you think this is out of scope, we can leave it as it is for the time being.

**Comment by dnoegel** [comment]
Regarding the **menu.xml**: I like it a lot - if possible, please make the "action" default to "index", so that we don't have to teach everyone to type "index" in there :)

**config.xml**: Looks good for me as well, scoping and translation are nice to maintain this way. 
Perhaps we should find a standard for the "form" as well - either as a wrapping "form" node, where all the corresponding elements sit in - or as an "form" attribute on each element node. By default shopware will put "Other" as form (\Shopware_Components_Plugin_Bootstrap::initForm) - but some plugin vendors do something like this in order to bind their configuration to shopware's basic settings.

```
$form = $this->Form(…);
$form->setParent(/* any other form from the basic settings */);
```

I think we need to have some way to define the form anyway (e.g. when exporting the shopware config later on). So perhaps its worth to define it right away, so we don't need to maintain to standards later on?

**Comment by bcremer** [comment]
I created a dedicated Repository to discuss the new schmas here: https://github.com/bcremer/shopware-plugin-schemas

**Comment by bcremer** [comment]
Regarding  "action" should default to "index":
XSD can not provide default values for elements, so that must be implemented in the (PHP-)reader.
But yes, `action` should not be required.

**Comment by bcremer** [comment]
Closed this issue, please continue discussion here: https://github.com/bcremer/shopware-plugin-schemas
